source 'http://rubygems.org'

gem 'rails', '3.2.11'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'pg'
gem "postgis_adapter", "~> 0.8.1"
gem "activerecord-postgis-adapter"
gem "rgeo-activerecord"
gem "rgeo"

gem 'libxml-ruby'

gem "devise", "~> 2.2.4"
gem "devise_suspendable", "~> 0.6.1"

gem "will_paginate", "~> 3.0.4"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.2.3"
  gem 'coffee-rails', "~> 3.2.1"
  gem 'uglifier'
end

gem 'jquery-rails'
gem 'execjs'
gem 'therubyracer'
gem "client_side_validations", "~> 3.2.5"

gem 'faker', '0.3.1'


group :development do
   gem 'rspec-rails'
   #gem 'annotate', :git => 'git://github.com/ctran/annotate_models.git'
   gem "annotate", "~> 2.5.0"
end

group :test do
   gem "rspec", "~> 2.13.0"
   gem 'webrat'
   gem "factory_girl", "~> 4.2.0"
   gem "factory_girl_rails", "~> 4.2.1"
end



# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

